2024-09-04 14:03:10,922 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:03:10,922 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_140310-a40uad22/logs/debug.log
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_140310-a40uad22/logs/debug-internal.log
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:03:10,923 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:03:10,925 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:03:10,925 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:03:10,932 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:03:10,932 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:03:10,932 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:03:10,935 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:04:40,986 ERROR   MainThread:398109 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:04:41,026 ERROR   MainThread:398109 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:06:51,638 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_140651-cncddl7r/logs/debug.log
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_140651-cncddl7r/logs/debug-internal.log
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:06:51,639 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:06:51,641 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:06:51,641 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:06:51,648 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:06:51,648 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:06:51,648 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:06:51,652 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:06:52,387 ERROR   MainThread:398109 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-04 14:06:52,427 ERROR   MainThread:398109 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_141132-1ncvidl3/logs/debug.log
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_141132-1ncvidl3/logs/debug-internal.log
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:11:32,062 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:11:32,064 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:11:32,065 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:11:32,071 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:11:32,071 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:11:32,071 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:11:32,074 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:13:02,128 ERROR   MainThread:398109 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:13:02,169 ERROR   MainThread:398109 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:13:23,251 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:13:23,251 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_141323-anuwfr1p/logs/debug.log
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_141323-anuwfr1p/logs/debug-internal.log
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:13:23,252 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:13:23,254 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:13:23,255 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:13:23,261 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:13:23,261 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:13:23,261 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:13:23,265 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:13:23,965 INFO    MainThread:398109 [wandb_run.py:_on_init():2254] communicating current version
2024-09-04 14:13:53,970 INFO    MainThread:398109 [wandb_init.py:init():800] starting run threads in backend
2024-09-04 14:14:23,992 INFO    MainThread:398109 [wandb_run.py:_console_start():2233] atexit reg
2024-09-04 14:14:23,992 INFO    MainThread:398109 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-09-04 14:14:23,992 INFO    MainThread:398109 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-09-04 14:14:23,992 INFO    MainThread:398109 [wandb_run.py:_redirect():2178] Redirects installed.
2024-09-04 14:14:23,993 INFO    MainThread:398109 [wandb_init.py:init():841] run started, returning control to user process
2024-09-04 14:14:24,216 INFO    MainThread:398109 [wandb_run.py:_config_callback():1342] config_cb None None {'vocab_size': 30006, 'max_position_embeddings': 1026, 'd_model': 768, 'encoder_ffn_dim': 3072, 'encoder_layers': 6, 'encoder_attention_heads': 16, 'decoder_ffn_dim': 3072, 'decoder_layers': 6, 'decoder_attention_heads': 16, 'dropout': 0.1, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'activation_function': 'gelu', 'init_std': 0.02, 'encoder_layerdrop': 0.0, 'decoder_layerdrop': 0.0, 'classifier_dropout': 0.1, 'use_cache': True, 'num_hidden_layers': 6, 'scale_embedding': False, 'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'torch_dtype': None, 'use_bfloat16': False, 'tf_legacy_loss': False, 'pruned_heads': {}, 'tie_word_embeddings': True, 'is_encoder_decoder': True, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'num_beam_groups': 1, 'diversity_penalty': 0.0, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'chunk_size_feed_forward': 0, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': 2, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'architectures': ['BartForConditionalGeneration'], 'finetuning_task': None, 'id2label': {0: 'NEGATIVE', 1: 'POSITIVE'}, 'label2id': {'NEGATIVE': 0, 'POSITIVE': 1}, 'tokenizer_class': None, 'prefix': None, 'bos_token_id': 0, 'pad_token_id': 3, 'eos_token_id': 1, 'sep_token_id': None, 'decoder_start_token_id': 2, 'task_specific_params': None, 'problem_type': None, '_name_or_path': 'digit82/kobart-summarization', 'transformers_version': '4.35.2', 'add_bias_logits': False, 'add_final_layer_norm': False, 'classif_dropout': 0.1, 'do_blenderbot_90_layernorm': False, 'extra_pos_embeddings': 2, 'force_bos_token_to_be_generated': False, 'model_type': 'bart', 'normalize_before': False, 'normalize_embedding': True, 'static_position_embeddings': False, 'output_dir': './', 'overwrite_output_dir': True, 'do_train': True, 'do_eval': True, 'do_predict': False, 'evaluation_strategy': 'epoch', 'prediction_loss_only': False, 'per_device_train_batch_size': 25, 'per_device_eval_batch_size': 32, 'per_gpu_train_batch_size': None, 'per_gpu_eval_batch_size': None, 'gradient_accumulation_steps': 1, 'eval_accumulation_steps': None, 'eval_delay': 0, 'learning_rate': 1e-05, 'weight_decay': 0.01, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 20, 'max_steps': -1, 'lr_scheduler_type': 'cosine', 'warmup_ratio': 0.1, 'warmup_steps': 0, 'log_level': 'passive', 'log_level_replica': 'warning', 'log_on_each_node': True, 'logging_dir': './logs', 'logging_strategy': 'epoch', 'logging_first_step': False, 'logging_steps': 500, 'logging_nan_inf_filter': True, 'save_strategy': 'epoch', 'save_steps': 500, 'save_total_limit': 5, 'save_safetensors': True, 'save_on_each_node': False, 'no_cuda': False, 'use_cpu': False, 'use_mps_device': False, 'seed': 42, 'data_seed': None, 'jit_mode_eval': False, 'use_ipex': False, 'bf16': False, 'fp16': True, 'fp16_opt_level': 'O1', 'half_precision_backend': 'auto', 'bf16_full_eval': False, 'fp16_full_eval': False, 'tf32': None, 'local_rank': 0, 'ddp_backend': None, 'tpu_num_cores': None, 'tpu_metrics_debug': False, 'debug': [], 'dataloader_drop_last': False, 'eval_steps': None, 'dataloader_num_workers': 0, 'past_index': -1, 'run_name': './', 'disable_tqdm': False, 'remove_unused_columns': True, 'label_names': None, 'load_best_model_at_end': True, 'metric_for_best_model': 'loss', 'greater_is_better': False, 'ignore_data_skip': False, 'fsdp': [], 'fsdp_min_num_params': 0, 'fsdp_config': {'min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False}, 'fsdp_transformer_layer_cls_to_wrap': None, 'deepspeed': None, 'label_smoothing_factor': 0.0, 'optim': 'adamw_torch', 'optim_args': None, 'adafactor': False, 'group_by_length': False, 'length_column_name': 'length', 'report_to': ['wandb'], 'ddp_find_unused_parameters': None, 'ddp_bucket_cap_mb': None, 'ddp_broadcast_buffers': None, 'dataloader_pin_memory': True, 'skip_memory_metrics': True, 'use_legacy_prediction_loop': False, 'push_to_hub': False, 'resume_from_checkpoint': None, 'hub_model_id': None, 'hub_strategy': 'every_save', 'hub_token': '<HUB_TOKEN>', 'hub_private_repo': False, 'hub_always_push': False, 'gradient_checkpointing': False, 'gradient_checkpointing_kwargs': None, 'include_inputs_for_metrics': False, 'fp16_backend': 'auto', 'push_to_hub_model_id': None, 'push_to_hub_organization': None, 'push_to_hub_token': '<PUSH_TO_HUB_TOKEN>', 'mp_parameters': '', 'auto_find_batch_size': False, 'full_determinism': False, 'torchdynamo': None, 'ray_scope': 'last', 'ddp_timeout': 1800, 'torch_compile': False, 'torch_compile_backend': None, 'torch_compile_mode': None, 'dispatch_batches': None, 'split_batches': False, 'include_tokens_per_second': False, 'neftune_noise_alpha': None, 'sortish_sampler': False, 'predict_with_generate': True, 'generation_max_length': 100, 'generation_num_beams': None, 'generation_config': None}
2024-09-04 14:14:24,228 WARNING MsgRouterThr:398109 [router.py:message_loop():77] message_loop has been closed
2024-09-04 14:14:24,228 WARNING MsgRouterThr:398109 [router.py:message_loop():77] message_loop has been closed
2024-09-04 14:30:06,957 INFO    MainThread:398109 [wandb_run.py:_finish():1962] finishing run dj-ai/my-project/anuwfr1p
2024-09-04 14:30:06,957 INFO    MainThread:398109 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-09-04 14:30:06,957 INFO    MainThread:398109 [wandb_run.py:_restore():2185] restore
2024-09-04 14:30:06,958 INFO    MainThread:398109 [wandb_run.py:_restore():2191] restore done
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_145126-lqoro3jc/logs/debug.log
2024-09-04 14:51:26,030 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_145126-lqoro3jc/logs/debug-internal.log
2024-09-04 14:51:26,032 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:51:26,032 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:51:26,033 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:51:26,033 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:51:26,035 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:51:26,035 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:51:26,042 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:51:26,042 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:51:26,042 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:51:26,045 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:52:56,098 ERROR   MainThread:398109 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:52:56,139 ERROR   MainThread:398109 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:54:00,805 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_145400-sf15dvyj/logs/debug.log
2024-09-04 14:54:00,806 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_145400-sf15dvyj/logs/debug-internal.log
2024-09-04 14:54:00,806 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:54:00,806 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:54:00,806 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:54:00,806 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:54:00,808 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:54:00,808 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:54:00,815 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:54:00,815 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:54:00,815 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:54:00,819 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:54:14,171 WARNING MainThread:398109 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-09-04 14:54:57,392 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:54:57,392 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:54:57,392 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:54:57,392 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_145457-pgnszp22/logs/debug.log
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_145457-pgnszp22/logs/debug-internal.log
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:54:57,393 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:54:57,396 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:54:57,396 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:54:57,402 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:54:57,402 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:54:57,403 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:54:57,408 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:55:59,111 WARNING MainThread:398109 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-09-04 14:57:27,102 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:57:27,102 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:57:27,102 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:57:27,102 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_145727-zq4v1wp5/logs/debug.log
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_145727-zq4v1wp5/logs/debug-internal.log
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:57:27,103 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:57:27,105 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:57:27,106 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:57:27,112 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:57:27,112 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:57:27,112 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:57:27,116 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:58:57,170 ERROR   MainThread:398109 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:58:57,210 ERROR   MainThread:398109 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 14:59:33,078 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 14:59:33,078 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Configure stats pid to 398109
2024-09-04 14:59:33,078 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 14:59:33,078 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_145933-lzc5u8s8/logs/debug.log
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_145933-lzc5u8s8/logs/debug-internal.log
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_init.py:init():564] calling init triggers
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 14:59:33,079 INFO    MainThread:398109 [wandb_init.py:init():614] starting backend
2024-09-04 14:59:33,080 INFO    MainThread:398109 [wandb_init.py:init():618] setting up manager
2024-09-04 14:59:33,082 INFO    MainThread:398109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 14:59:33,082 INFO    MainThread:398109 [wandb_init.py:init():624] backend started and connected
2024-09-04 14:59:33,088 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 14:59:33,089 INFO    MainThread:398109 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 14:59:33,089 INFO    MainThread:398109 [wandb_init.py:init():716] updated telemetry
2024-09-04 14:59:33,093 INFO    MainThread:398109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 14:59:48,571 WARNING MainThread:398109 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
