2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Configure stats pid to 401864
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_150108-scr3beo6/logs/debug.log
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_150108-scr3beo6/logs/debug-internal.log
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_init.py:init():564] calling init triggers
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_init.py:init():614] starting backend
2024-09-04 15:01:08,427 INFO    MainThread:401864 [wandb_init.py:init():618] setting up manager
2024-09-04 15:01:08,429 INFO    MainThread:401864 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 15:01:08,429 INFO    MainThread:401864 [wandb_init.py:init():624] backend started and connected
2024-09-04 15:01:08,436 INFO    MainThread:401864 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 15:01:08,436 INFO    MainThread:401864 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 15:01:08,436 INFO    MainThread:401864 [wandb_init.py:init():716] updated telemetry
2024-09-04 15:01:08,440 INFO    MainThread:401864 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 15:01:09,171 ERROR   MainThread:401864 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-04 15:01:09,212 ERROR   MainThread:401864 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-04 15:01:31,544 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 15:01:31,544 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Configure stats pid to 401864
2024-09-04 15:01:31,544 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 15:01:31,544 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 15:01:31,544 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_150131-mtxgnr22/logs/debug.log
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_150131-mtxgnr22/logs/debug-internal.log
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_init.py:init():564] calling init triggers
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_init.py:init():614] starting backend
2024-09-04 15:01:31,545 INFO    MainThread:401864 [wandb_init.py:init():618] setting up manager
2024-09-04 15:01:31,547 INFO    MainThread:401864 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 15:01:31,547 INFO    MainThread:401864 [wandb_init.py:init():624] backend started and connected
2024-09-04 15:01:31,553 INFO    MainThread:401864 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 15:01:31,554 INFO    MainThread:401864 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 15:01:31,554 INFO    MainThread:401864 [wandb_init.py:init():716] updated telemetry
2024-09-04 15:01:31,557 INFO    MainThread:401864 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 15:01:35,210 WARNING MainThread:401864 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-09-04 15:02:55,890 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-09-04 15:02:55,890 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Configure stats pid to 401864
2024-09-04 15:02:55,890 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-09-04 15:02:55,890 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from /dj2/code/wandb/settings
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_init.py:_log_setup():524] Logging user logs to /dj2/code/wandb/run-20240904_150255-zci6xi92/logs/debug.log
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_init.py:_log_setup():525] Logging internal logs to /dj2/code/wandb/run-20240904_150255-zci6xi92/logs/debug-internal.log
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_init.py:init():564] calling init triggers
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-09-04 15:02:55,891 INFO    MainThread:401864 [wandb_init.py:init():614] starting backend
2024-09-04 15:02:55,892 INFO    MainThread:401864 [wandb_init.py:init():618] setting up manager
2024-09-04 15:02:55,896 INFO    MainThread:401864 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-04 15:02:55,896 INFO    MainThread:401864 [wandb_init.py:init():624] backend started and connected
2024-09-04 15:02:55,904 INFO    MainThread:401864 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-09-04 15:02:55,904 INFO    MainThread:401864 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-04 15:02:55,904 INFO    MainThread:401864 [wandb_init.py:init():716] updated telemetry
2024-09-04 15:02:55,908 INFO    MainThread:401864 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-04 15:02:56,629 WARNING MsgRouterThr:401864 [router.py:message_loop():77] message_loop has been closed
2024-09-04 15:04:25,962 ERROR   MainThread:401864 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-04 15:04:26,003 ERROR   MainThread:401864 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
